PrimeraPracticaNetCoreZapatillas/Models/ErrorViewModel.cs
namespace PrimeraPracticaNetCoreZapatillas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrimeraPracticaNetCoreZapatillas/Models/Imagen.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PrimeraPracticaNetCoreZapatillas.Models
{
    [Table("IMAGENESZAPASPRACTICA")]
    public class Imagen
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImagen { get; set; }
        [Column("IDPRODUCTO")]
        public int IdProducto{ get; set; }
        [Column("IMAGEN")]
        public string ImagenZapa { get; set; }
    }
}

PrimeraPracticaNetCoreZapatillas/Models/ModelPaginacionZapatillas.cs
namespace PrimeraPracticaNetCoreZapatillas.Models
{
    public class ModelPaginacionZapatillas
    {
        public int NumeroRegistros { get; set; }
        public Imagen ImagenZap { get; set; }
        //public Departamento DepartamentoElegido { get; set; }
        public Zapatilla Zapatilla { get; set; }
    }
}

PrimeraPracticaNetCoreZapatillas/Models/Zapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PrimeraPracticaNetCoreZapatillas.Models
{
    [Table("ZAPASPRACTICA")]
    public class Zapatilla
    {
        [Key]
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }

        [Column("PRECIO")]
        public int Precio { get; set; }
    }
}

PrimeraPracticaNetCoreZapatillas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PrimeraPracticaNetCoreZapatillas.Models;
using System.Diagnostics;

namespace PrimeraPracticaNetCoreZapatillas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrimeraPracticaNetCoreZapatillas/Controllers/ZapatillasController.cs
using Microsoft.AspNetCore.Mvc;
using PrimeraPracticaNetCoreZapatillas.Models;
using PrimeraPracticaNetCoreZapatillas.Repositories;

namespace PrimeraPracticaNetCoreZapatillas.Controllers
{
    public class ZapatillasController : Controller
    {
        private RepositoryZapatillas repo;

        public ZapatillasController(RepositoryZapatillas repo)
        {
            this.repo = repo;
        }
        public async Task<IActionResult> Index()
        {
            List<Zapatilla> zapatillas = await this.repo.GetZapatillasAsync();
            return View(zapatillas);
        }

        public async Task<IActionResult> Details(int? posicion,int idzapatilla)
        {

            if (posicion == null)
            {
                posicion = 1;
            }
            ModelPaginacionZapatillas model = await
                this.repo.GetImagenesZapatillaAsync
                (posicion.Value, idzapatilla);
            //Zapatilla zapatilla =
            //    await this.repo.FindDepartamentosAsync(idzapatilla);
            Zapatilla zapatilla = await this.repo.FindZapatillaAsync(idzapatilla);
            ViewData["ZAPATILLASELECCIONADA"] = zapatilla;
            ViewData["REGISTROS"] = model.NumeroRegistros;
            ViewData["ZAPATILLA"] = idzapatilla;
            int siguiente = posicion.Value + 1;
            //DEBEMOS COMPROBAR QUE NO PASAMOS DEL NUMERO DE REGISTROS
            if (siguiente > model.NumeroRegistros)
            {
                //EFECTO OPTICO
                siguiente = model.NumeroRegistros;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }
            ViewData["ULTIMO"] = model.NumeroRegistros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;
            

            return View(model.Zapatilla);
        }

        


        public async Task<IActionResult> _ImagenesZapatillaPartial(int? posicion, int idzapatilla)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            ModelPaginacionZapatillas model =
                await this.repo.GetImagenesZapatillaAsync
                (posicion.Value, idzapatilla);
            int numeroRegistros = model.NumeroRegistros;
            int siguiente = posicion.Value + 1;
            if (siguiente > numeroRegistros)
            {
                siguiente = numeroRegistros;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }
            ViewData["ÚLTIMO"] = numeroRegistros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["ZAPATILLASELECCIONADA"] = model.Zapatilla;
            ViewData["POSICION"] = posicion;
            return PartialView("_ImagenesZapatillaPartial", model.ImagenZap);
        }

        public async Task<IActionResult> NuevasImagenes()
        {

            List<Zapatilla> zapatillas = await this.repo.GetZapatillasAsync();
            return View(zapatillas);
        }

        [HttpPost]

        public async Task<IActionResult> NuevasImagenes(string zapatilla,List<string> imagen)
        {
            List<string> imagenes = imagen;
            int idZapatilla = int.Parse(zapatilla);
            List<Zapatilla> zapatillas = await this.repo.GetZapatillasAsync();

            await this.repo.InsertImagenesAsync(idZapatilla, imagenes);
            ViewData["MENSAJES"] = "Imagnees insertadas correctamente";
            return View(zapatillas);
        }
    }
}

PrimeraPracticaNetCoreZapatillas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PrimeraPracticaNetCoreZapatillas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimeraPracticaNetCoreZapatillas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrimeraPracticaNetCoreZapatillas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimeraPracticaNetCoreZapatillas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatillas" asp-action="Index">Zapatillas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatillas" asp-action="NuevasImagenes">Nuevas Imagenes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PrimeraPracticaNetCoreZapatillas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PrimeraPracticaNetCoreZapatillas/Views/Zapatillas/Details.cshtml
@model Imagen 

@{
    Zapatilla zapatilla =
            ViewData["ZAPATILLASELECCIONADA"] as Zapatilla;
}


@{
    ViewData["Title"] = "Detaills";
}

<h1>Detaills</h1>

<ul class="list-group">
    <li class="list-group-item list-group-item-danger">
        Nombre :: @zapatilla.Nombre
    </li>
    <li class="list-group-item list-group-item-info">
        Descripcion: @zapatilla.Descripcion
    </li>
    <li class="list-group-item list-group-item-info">
        Precio: @zapatilla.Precio
    </li>
</ul>


<div id="contenido" style="background-color: lightgreen"></div>

@section Scripts {
    <script>
        function loadImagenPaginacion(posicion) {
            $(function () {
                $("#contenido").load("/Zapatillas/_ImagenesZapatillaPartial?posicion="
                    + posicion + "&idzapatilla=" + @zapatilla.IdProducto);
            });
        }

        loadImagenPaginacion(1);
    </script>
}

PrimeraPracticaNetCoreZapatillas/Views/Zapatillas/Index.cshtml
@model IEnumerable<PrimeraPracticaNetCoreZapatillas.Models.Zapatilla>

@{
    ViewData["Title"] = "Index";
}

<h1>Listado Zapatillas</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdProducto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <a asp-controller="Zapatillas" asp-action="Details" asp-route-idzapatilla="@item.IdProducto" class="btn btn-dark">Detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

PrimeraPracticaNetCoreZapatillas/Views/Zapatillas/NuevasImagenes.cshtml
@model List<Zapatilla>


    <h1>Nuevas Imagenes Zapatillas</h1>

<h3>@ViewData["MENSAJES"]</h3>

    <button  class="btn btn-warning" onclick="addInput()">
        Añadir nuevo campo Jquery
   </button>

   <hr/>

    <form method="post" id="formulario">

    <button class="btn btn-info">
        Añadir imagenes POST
    </button>
    <select class="form-control" name="zapatilla">
            @foreach (Zapatilla zapa in Model)
        {
            <option  value="@zapa.IdProducto">@zapa.Nombre</option>
        }
        </select>

        <input type="text" name="imagen" class="form-control" />
        

    </form>


@section Scripts {
    <script>
        function addInput() {
            $(function () {
                var nuevoinput = $('<input type="text" name="imagen" class="form-control"/>');
                $("#formulario").append(nuevoinput);
            });
        }
                
    </script>
}

PrimeraPracticaNetCoreZapatillas/Views/Zapatillas/_ImagenesZapatillaPartial.cshtml
@model Imagen
@{
    Zapatilla zapa = ViewData["ZAPATILLASELECCIONADA"] as Zapatilla;
}


@if ((int)@ViewData["ÚLTIMO"]!=0)
{
    <h3 class="mt-3">
        Imagen @ViewData["POSICION"] de @ViewData["ÚLTIMO"]
    </h3>
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item">
            <button onclick="loadImagenPaginacion(1)" class="btn">
                Primero
            </button>
        </li>
        <li class="list-group-item">
            <button onclick="loadImagenPaginacion(@ViewData["ANTERIOR"])" class="btn">
                Anterior
            </button>
        </li>
        <li class="list-group-item">
            <button onclick="loadImagenPaginacion(@ViewData["SIGUIENTE"])" class="btn">
                Siguiente
            </button>
        </li>
        <li class="list-group-item">
            <button onclick="loadImagenPaginacion(@ViewData["ÚLTIMO"])" class="btn">
                Último
            </button>
        </li>
    </ul>

<div>
    <img src="@Model.ImagenZapa" style="width:250px; height:250px" />
</div>
}
else
{
    <h2>No existen registros para este departamento</h2>
}